spring:
  application:
    name: gateway-service
server:
  port: 8768
eureka:
  instance:
      hostname: localhost
      appname: gateway
      instance-id: gateway:port-8768
      prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://111.231.189.44:8761/eureka
zuul:
  routes:
    order-service:
      path: /order-service/**
      serviceId: order-service
