server:
  port: 8762
# druid
spring:
  application:
    name: account-service
  datasource:
    druid:
      url: jdbc:mysql://47.75.85.48:3306/spring-cloud-test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: MyNewPass4!
  aop:
    auto: true
  freemarker:
    request-context-attribute: request
    prefer-file-system-access: false
    settings.number_format: 0.##
# mybatis
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.itmuch.cloud.study.account.entity
# eureka
eureka:
  instance:
    hostname: localhost
    appname: account-service
    instance-id: account-service:port-8762
    prefer-ip-address: true
  client:
    service-url:
       defaultZone: http://111.231.189.44:8761/eureka
#swagger
swagger:
  base-package: com.com.itmuch.cloud.study.account.controller
# logging
logging:
  level: com.itmuch.cloud.study.account.entity
  config: classpath:logging-config.xml

